#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
#  Madrasah Madinatul Ilm — PythonAnywhere Deployment Script
#  Muhammadiyah Trust, Gopalpur, Siwan, Bihar
# ───────────────────────────────────────────────────────────────────────────────
#  USAGE (run from your PythonAnywhere Bash console):
#
#    1. Upload your project code to PythonAnywhere (Files tab or git clone)
#    2. Open a Bash console on PythonAnywhere
#    3. cd to the project root (where manage.py lives), e.g.:
#         cd /home/<yourusername>/madinatulilm
#    4. Run:
#         bash deploy_pythonanywhere.sh
#
#  The script will:
#    • Create / activate a virtualenv
#    • Install all dependencies
#    • Write a production .env
#    • Run migrations
#    • Seed all content (site text, trustees, ijazah, programs, hadiths, links)
#    • Create the admin superuser
#    • Collect static files
# ═══════════════════════════════════════════════════════════════════════════════

set -e   # exit immediately on any error

# ── 0. Colours ─────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERR]${NC}   $*"; exit 1; }

echo ""
echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Madrasah Madinatul Ilm — PythonAnywhere Deployment  ${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════════${NC}"
echo ""

# ── 1. Detect project root ─────────────────────────────────────────────────────
if [ ! -f "manage.py" ]; then
    error "manage.py not found. Run this script from the project root (where manage.py lives)."
fi
PROJECT_DIR="$(pwd)"
info "Project root: $PROJECT_DIR"

# ── 2. PythonAnywhere username & domain ───────────────────────────────────────
PA_USER="madrasahmadinatulilm"
PA_DOMAIN="madrasahmadinatulilm.pythonanywhere.com"
CUSTOM_DOMAIN="muhammadiyyahtrust.org"
info "PythonAnywhere user : $PA_USER"
info "PythonAnywhere domain: $PA_DOMAIN"
info "Custom domain       : $CUSTOM_DOMAIN (www.$CUSTOM_DOMAIN)"

# ── 3. Virtual environment ────────────────────────────────────────────────────
# PythonAnywhere provides Python 3.13 — Django 5.1.3 requires >= 3.10
VENV_DIR="$HOME/venv_madinatulilm"

# Prefer python3.13, fall back gracefully
if command -v python3.13 &>/dev/null; then
    PY_BIN="python3.13"
elif command -v python3 &>/dev/null; then
    PY_BIN="python3"
    warn "python3.13 not found — falling back to $(python3 --version). Ensure your PythonAnywhere Web tab is set to Python 3.13."
else
    error "No Python 3 found. On PythonAnywhere go to Web tab → Python version → select 3.13."
fi
info "Using Python binary: $PY_BIN ($(${PY_BIN} --version))"

if [ -d "$VENV_DIR" ]; then
    info "Virtualenv already exists at $VENV_DIR — reusing"
else
    info "Creating virtualenv at $VENV_DIR ..."
    "$PY_BIN" -m venv "$VENV_DIR"
    success "Virtualenv created"
fi

# Activate
source "$VENV_DIR/bin/activate"
success "Virtualenv activated: $(python --version)"

# ── 4. Install dependencies ───────────────────────────────────────────────────
info "Installing Python dependencies from requirements.txt ..."
pip install --upgrade pip --quiet
pip install -r "$PROJECT_DIR/requirements.txt" --quiet
success "Dependencies installed"

# ── 5. Write production .env ──────────────────────────────────────────────────
ENV_FILE="$PROJECT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    warn ".env already exists — backing up to .env.bak and overwriting"
    cp "$ENV_FILE" "$ENV_FILE.bak"
fi

# Generate a new secret key
SECRET=$(python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())")

cat > "$ENV_FILE" <<EOF
# ── Madrasah Madinatul Ilm — Production .env ──────────────────────────────────
# Generated by deploy_pythonanywhere.sh on $(date)

DEBUG=False
SECRET_KEY=${SECRET}
ALLOWED_HOSTS=${PA_DOMAIN},www.${PA_DOMAIN},${CUSTOM_DOMAIN},www.${CUSTOM_DOMAIN},127.0.0.1,localhost

# ── Database: MySQL (PythonAnywhere) ──────────────────────────────────────────
DB_ENGINE=django.db.backends.mysql
DB_NAME=madrasahmadinatu\$muhammadiyyah_db
DB_USER=madrasahmadinatu
DB_PASSWORD=Yaalimadad@786
DB_HOST=madrasahmadinatulilm.mysql.pythonanywhere-services.com
DB_PORT=3306
EOF

success ".env written to $ENV_FILE"

# ── 6. Export env vars for this session ──────────────────────────────────────
export DEBUG=False
export SECRET_KEY="$SECRET"
export ALLOWED_HOSTS="${PA_DOMAIN},www.${PA_DOMAIN},${CUSTOM_DOMAIN},www.${CUSTOM_DOMAIN},127.0.0.1,localhost"
export DB_ENGINE=django.db.backends.mysql
export DB_NAME='madrasahmadinatu$muhammadiyyah_db'
export DB_USER=madrasahmadinatu
export DB_PASSWORD='Yaalimadad@786'
export DB_HOST=madrasahmadinatulilm.mysql.pythonanywhere-services.com
export DB_PORT=3306

# ── 7. Run database migrations ────────────────────────────────────────────────
info "Running database migrations ..."
cd "$PROJECT_DIR"
python manage.py migrate --noinput
success "Migrations complete"

# ── 8. Seed all content ───────────────────────────────────────────────────────
info "Seeding site content (trustees, ijazah, programs, categories, biographies) ..."
python manage.py seed_content
success "seed_content complete"

info "Seeding hadiths and partner page ..."
python manage.py seed_hadiths
success "seed_hadiths complete"

info "Seeding useful Islamic resource links ..."
python manage.py seed_useful_links
success "seed_useful_links complete"

# ── 9. Create admin superuser ─────────────────────────────────────────────────
info "Creating admin superuser ..."
# Override defaults via env if desired:
#   export DJANGO_SUPERUSER_USERNAME=minhal
#   export DJANGO_SUPERUSER_EMAIL=admin@madinatulilm.com
#   export DJANGO_SUPERUSER_PASSWORD='YourNewPassword!'
python manage.py create_superuser
success "Superuser ready"

# ── 10. Collect static files ──────────────────────────────────────────────────
info "Collecting static files to staticfiles/ ..."
python manage.py collectstatic --noinput --clear
success "Static files collected to: $PROJECT_DIR/staticfiles/"

# ── 11. Media folder permissions ─────────────────────────────────────────────
if [ -d "$PROJECT_DIR/media" ]; then
    chmod -R 755 "$PROJECT_DIR/media"
    success "Media folder permissions set"
fi

# ── 12. Summary ───────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅  Deployment complete!                             ${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${CYAN}Site URL${NC}        : https://${PA_DOMAIN}"
echo -e "  ${CYAN}Admin panel${NC}     : https://${PA_DOMAIN}/admin/"
echo -e "  ${CYAN}Admin username${NC}  : ${DJANGO_SUPERUSER_USERNAME:-admin}"
echo -e "  ${CYAN}Admin password${NC}  : ${DJANGO_SUPERUSER_PASSWORD:-MIL@admin2026!}"
echo ""
echo -e "  ${YELLOW}⚠  IMPORTANT — after first login:${NC}"
echo -e "     1. Go to Admin → Users → admin → Change password"
echo -e "     2. Go to Admin → Core → Site Settings → add your site name, logo, contact"
echo -e "     3. Upload media files (trustees photos, ijazah images, gallery) if not already present"
echo ""
echo -e "  ${CYAN}PythonAnywhere Web tab — WSGI config:${NC}"
echo -e "     • Source code     : $PROJECT_DIR"
echo -e "     • Virtualenv      : $VENV_DIR"
echo -e "     • WSGI file path  : $PROJECT_DIR/madinatulilm/wsgi.py"
echo -e "     • Static URL      : /static/   →  $PROJECT_DIR/staticfiles/"
echo -e "     • Media URL       : /media/    →  $PROJECT_DIR/media/"
echo ""
echo -e "  ${CYAN}After setting up the Web tab, click 'Reload' to go live.${NC}"
echo ""
