# Generated by Django 5.2.12 on 2026-03-29 03:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='About Us', max_length=300)),
                ('body_en', ckeditor.fields.RichTextField()),
                ('body_ar', ckeditor.fields.RichTextField(blank=True)),
                ('body_ur', ckeditor.fields.RichTextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('quran', 'Qurʾān'), ('hadith', 'Hadith'), ('Fiqh', 'Fiqh'), ('usul', 'Usūl al-Fiqh'), ('kalam', 'Kalām & ʿAqīdah'), ('akhlaq', 'Akhlāq'), ('rational', 'Rational Sciences'), ('language', 'Language & Literature')], max_length=20)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', ckeditor.fields.RichTextField(blank=True)),
                ('description_ar', ckeditor.fields.RichTextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('name_ur', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founder/')),
                ('biography_en', ckeditor.fields.RichTextField(blank=True)),
                ('biography_ur', ckeditor.fields.RichTextField(blank=True)),
                ('biography_ar', ckeditor.fields.RichTextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Ijazah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('from_scholar', models.CharField(max_length=200)),
                ('ijazah_type', models.CharField(choices=[('riwayat', 'Ijazah Naql Riwayat'), ('wakalat', 'Ijazah Wakalat'), ('sahm_imam', 'Ijazah Sahm Imam'), ('other', 'Other')], default='riwayat', max_length=20)),
                ('image', models.ImageField(upload_to='ijazat/')),
                ('description', models.TextField(blank=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ijazat',
                'ordering': ['sort_order', 'from_scholar'],
            },
        ),
        migrations.CreateModel(
            name='MadrasahGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Madrasah Gallery',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Our Mission', max_length=300)),
                ('body_en', ckeditor.fields.RichTextField()),
                ('body_ar', ckeditor.fields.RichTextField(blank=True)),
                ('body_ur', ckeditor.fields.RichTextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(default='Madrasah Madinatul Ilm', max_length=200)),
                ('site_name_ar', models.CharField(default='مدرسة مدينة العلم', max_length=200)),
                ('site_name_ur', models.CharField(default='مدرسہ مدینۃ العلم', max_length=200)),
                ('tagline_en', models.CharField(default='Centre of Faqāhat', max_length=300)),
                ('trust_name', models.CharField(default='Muhammadiyah Trust', max_length=200)),
                ('established', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('address', models.TextField(blank=True)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('google_maps_embed', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trustees/')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Our Vision', max_length=300)),
                ('body_en', ckeditor.fields.RichTextField()),
                ('body_ar', ckeditor.fields.RichTextField(blank=True)),
                ('body_ur', ckeditor.fields.RichTextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('body_en', ckeditor.fields.RichTextField()),
                ('body_ar', ckeditor.fields.RichTextField(blank=True)),
                ('body_ur', ckeditor.fields.RichTextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
