# Generated by Django 5.2.12 on 2026-03-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(help_text='Arabic text of the hadith')),
                ('text_en', models.TextField(blank=True, help_text='English translation')),
                ('text_ur', models.TextField(blank=True, help_text='Urdu translation')),
                ('text_fa', models.TextField(blank=True, help_text='Persian translation')),
                ('source', models.CharField(help_text='e.g. Al-Kafi, Vol.1, p.30', max_length=300)),
                ('narrator', models.CharField(blank=True, help_text='e.g. Imam Ali (AS)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hadith Quote',
                'verbose_name_plural': 'Hadith Quotes (ʿIlm)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_en', models.TextField(blank=True)),
                ('intro_ar', models.TextField(blank=True)),
                ('intro_ur', models.TextField(blank=True)),
                ('intro_fa', models.TextField(blank=True)),
                ('bank_details', models.TextField(blank=True, help_text='Full bank details text (will be rendered as preformatted text)')),
                ('qr_code_1', models.ImageField(blank=True, help_text='QR Code 1 (e.g. ICICI)', null=True, upload_to='partner/')),
                ('qr_code_2', models.ImageField(blank=True, help_text='QR Code 2 (e.g. SBI)', null=True, upload_to='partner/')),
                ('tax_note', models.CharField(blank=True, default='Tax Benefit: Applied For', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Be A Partner Page',
                'verbose_name_plural': 'Be A Partner Page',
            },
        ),
    ]
