# Generated by Django 5.2.12 on 2026-04-01 04:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hadithquote_partnerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='body_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ar',
            field=models.CharField(blank=True, default='من نحن', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_fa',
            field=models.CharField(blank=True, default='درباره ما', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ur',
            field=models.CharField(blank=True, default='ہمارے بارے میں', max_length=300),
        ),
        migrations.AddField(
            model_name='missionsection',
            name='body_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='missionsection',
            name='title_ar',
            field=models.CharField(blank=True, default='مهمتنا', max_length=300),
        ),
        migrations.AddField(
            model_name='missionsection',
            name='title_fa',
            field=models.CharField(blank=True, default='مأموریت ما', max_length=300),
        ),
        migrations.AddField(
            model_name='missionsection',
            name='title_ur',
            field=models.CharField(blank=True, default='ہمارا مشن', max_length=300),
        ),
        migrations.AddField(
            model_name='visionsection',
            name='body_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='visionsection',
            name='title_ar',
            field=models.CharField(blank=True, default='رؤيتنا', max_length=300),
        ),
        migrations.AddField(
            model_name='visionsection',
            name='title_fa',
            field=models.CharField(blank=True, default='چشم\u200cانداز ما', max_length=300),
        ),
        migrations.AddField(
            model_name='visionsection',
            name='title_ur',
            field=models.CharField(blank=True, default='ہمارا وژن', max_length=300),
        ),
        migrations.AddField(
            model_name='welcomesection',
            name='body_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='welcomesection',
            name='title_fa',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='welcomesection',
            name='title_ur',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
