# Generated by Django 5.2.12 on 2026-04-01 07:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutsection_body_fa_aboutsection_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='biography_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
