# Generated by Django 5.2.12 on 2026-04-01 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_biography_fa_to_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='description_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='description_ur',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='title_ur',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
