# Generated by Django 5.2.12 on 2026-04-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_academicprogram_all_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maraji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Portrait photograph of the Marja — uploaded via admin. Appears in the homepage hero banner.', null=True, upload_to='maraji/')),
                ('name_en', models.CharField(help_text='English / transliterated name', max_length=200)),
                ('name_ar', models.CharField(blank=True, help_text='Full Arabic name (calligraphic form)', max_length=200)),
                ('name_ur', models.CharField(blank=True, help_text='Urdu name', max_length=200)),
                ('name_fa', models.CharField(blank=True, help_text='Persian / Farsi name', max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('title_ur', models.CharField(blank=True, max_length=300)),
                ('title_fa', models.CharField(blank=True, max_length=300)),
                ('role_en', models.CharField(blank=True, max_length=300)),
                ('role_ar', models.CharField(blank=True, max_length=300)),
                ('role_ur', models.CharField(blank=True, max_length=300)),
                ('role_fa', models.CharField(blank=True, max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('description_ur', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('affiliation_en', models.TextField(blank=True)),
                ('affiliation_ar', models.TextField(blank=True)),
                ('affiliation_ur', models.TextField(blank=True)),
                ('affiliation_fa', models.TextField(blank=True)),
                ('is_deceased', models.BooleanField(default=False, help_text='Check this if the scholar has passed away. The banner will display رحمة الله عليه instead of دام ظله الوارف.', verbose_name='Deceased (Rahmatullahi ʿAlayh)')),
                ('date_of_passing', models.DateField(blank=True, help_text='Optional — date of passing, displayed if deceased.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marjaʿ',
                'verbose_name_plural': 'Marājiʿ (Spiritual Authorities)',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
    ]
