# Generated by Django 5.2.12 on 2026-04-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_maraji_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Landscape image works best (min 1600×900 px). JPEG/WebP recommended.', upload_to='hero_banner/')),
                ('caption', models.CharField(blank=True, help_text='Optional internal caption (not shown on site).', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner Image',
                'verbose_name_plural': 'Hero Banner Images',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
    ]
