# Generated by Django 5.2.12 on 2026-04-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hero_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustee',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='Mark this trustee as the founder. Their card on the Trustees tab will link to the Founder biography page.', verbose_name='Is Founder'),
        ),
    ]
