# Generated by Django 5.2.12 on 2026-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trustee_member_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ijazah',
            options={'ordering': ['sort_order', 'from_scholar'], 'verbose_name_plural': 'Ijazah'},
        ),
        migrations.AlterModelOptions(
            name='trustee',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Our Team'},
        ),
        migrations.AlterField(
            model_name='founder',
            name='phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ijazah',
            name='image',
            field=models.ImageField(upload_to='ijazah/'),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
