# Generated by Django 5.2.12 on 2026-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_partnerpage_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='imamasr_bar_ar',
            field=models.CharField(blank=True, default='تحت ولاية الإمام صاحب العصر والزمان (عج)', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='imamasr_bar_en',
            field=models.CharField(blank=True, default='Under the Guardianship of Imām al-ʿAsr (ʿAJ)', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='imamasr_bar_fa',
            field=models.CharField(blank=True, default='زیر نظر امام عصر (عج)', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='imamasr_bar_ur',
            field=models.CharField(blank=True, default='امام العصر (عج) کی سرپرستی میں', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maraji_label_ar',
            field=models.CharField(blank=True, default='رحمه الله — مرجعنا الأعلى', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maraji_label_en',
            field=models.CharField(blank=True, default='In Memoriam — Our Revered Marjiʿ al-Taqlīd', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maraji_label_fa',
            field=models.CharField(blank=True, default='رحمة\u200cالله علیه — مرجع تقلید ما', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maraji_label_ur',
            field=models.CharField(blank=True, default='رحمۃ اللہ علیہ — ہمارے مرجع تقلید', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_imamasr_bar',
            field=models.BooleanField(default=True, help_text="Show the 'Imam al-Asr guardianship' bar below the Bismillah"),
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='qr_code_1',
            field=models.ImageField(blank=True, help_text='QR Code for Bank 1 (e.g. ICICI)', null=True, upload_to='partner/'),
        ),
        migrations.AlterField(
            model_name='partnerpage',
            name='qr_code_2',
            field=models.ImageField(blank=True, help_text='QR Code for Bank 2 (e.g. SBI)', null=True, upload_to='partner/'),
        ),
    ]
