# Generated by Django 5.2.12 on 2026-03-29 03:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShariaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kalam', 'Kalām & ʿAqīdah (Theology & Creed)'), ('akhlaq', 'Akhlāq (Ethics)'), ('fiqh', 'Fiqh (Jurisprudence)')], max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sharia Categories',
            },
        ),
        migrations.CreateModel(
            name='ShariaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('body_en', ckeditor.fields.RichTextField()),
                ('body_ar', ckeditor.fields.RichTextField(blank=True)),
                ('body_ur', ckeditor.fields.RichTextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='sharia/pdfs/')),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='sharia.shariacategory')),
            ],
            options={
                'verbose_name': 'Sharia Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
