# Generated by Django 5.2.12 on 2026-03-29 03:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('tafsir_hadith', 'Tafsīr & Hadith'), ('rijal', 'Rijāl (Science of Narrators)'), ('fiqh', 'Fiqh (Jurisprudence)'), ('usul', 'Usūl al-Fiqh'), ('kalam', 'Kalām & ʿAqīdah'), ('akhlaq', 'Akhlāq (Ethics)'), ('rational', 'Rational Sciences'), ('arabic', 'Arabic Literature'), ('misc', 'Miscellaneous')], max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Book Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=400)),
                ('title_ar', models.CharField(blank=True, max_length=400)),
                ('title_ur', models.CharField(blank=True, max_length=400)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('research', 'Research Paper'), ('fatwa', 'Fatwa Collection')], default='book', max_length=20)),
                ('description_en', ckeditor.fields.RichTextField(blank=True)),
                ('description_ar', ckeditor.fields.RichTextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('external_url', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, default='Arabic', max_length=100)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('published_year', models.CharField(blank=True, max_length=10)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.bookcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
