# Generated by Django 5.2.12 on 2026-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(choices=[('maraji', 'Marājiʿ Offices'), ('quran', 'Qurʾān & Tafsīr'), ('hadith', 'Hadith & Rijāl'), ('dua', 'Duʿāʾ & Ziyārat'), ('sharia', 'Fiqh & Fatāwā'), ('education', 'Islamic Education'), ('library', 'Digital Libraries'), ('other', 'Other Resources')], default='other', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class e.g. fas fa-globe', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Useful Link',
                'verbose_name_plural': 'Useful Links',
                'ordering': ['category', 'sort_order', 'title'],
            },
        ),
    ]
