# Generated by Django 5.2.12 on 2026-03-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('fiqh', 'Fiqh (Jurisprudence)'), ('aqeedah', 'ʿAqīdah (Creed)'), ('akhlaq', 'Akhlāq (Ethics)'), ('quran', 'Qurʾān'), ('hadith', 'Hadith'), ('general', 'General Islamic'), ('other', 'Other')], default='general', max_length=20)),
                ('question', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='Show question and answer publicly?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('answered_by', models.CharField(blank=True, max_length=200)),
                ('answer', models.TextField(blank=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
