# Generated by Django 5.2.12 on 2026-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, choices=[('', '— Select Country —'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('IQ', 'Iraq'), ('IR', 'Iran'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('BH', 'Bahrain'), ('OM', 'Oman'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('NO', 'Norway'), ('MY', 'Malaysia'), ('ID', 'Indonesia'), ('TR', 'Turkey'), ('EG', 'Egypt'), ('LB', 'Lebanon'), ('SY', 'Syria'), ('JO', 'Jordan'), ('AF', 'Afghanistan'), ('NP', 'Nepal'), ('LK', 'Sri Lanka'), ('NG', 'Nigeria'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('ZA', 'South Africa'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('MX', 'Mexico'), ('JP', 'Japan'), ('CN', 'China'), ('RU', 'Russia'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '— Select Gender —'), ('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='country',
            field=models.CharField(blank=True, choices=[('', '— Select Country —'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('IQ', 'Iraq'), ('IR', 'Iran'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('BH', 'Bahrain'), ('OM', 'Oman'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('NO', 'Norway'), ('MY', 'Malaysia'), ('ID', 'Indonesia'), ('TR', 'Turkey'), ('EG', 'Egypt'), ('LB', 'Lebanon'), ('SY', 'Syria'), ('JO', 'Jordan'), ('AF', 'Afghanistan'), ('NP', 'Nepal'), ('LK', 'Sri Lanka'), ('NG', 'Nigeria'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('ZA', 'South Africa'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('MX', 'Mexico'), ('JP', 'Japan'), ('CN', 'China'), ('RU', 'Russia'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '— Select Gender —'), ('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('fiqh', 'Fiqh (Jurisprudence)'), ('aqeedah', 'ʿAqīdah (Creed)'), ('akhlaq', 'Akhlāq (Ethics)'), ('quran', 'Qurʾān'), ('hadith', 'Hadith'), ('general', 'General Islamic'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
