# Generated by Django 5.2.12 on 2026-03-29 03:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('statement', 'Statement'), ('message', 'Issued Message'), ('meeting', 'Meeting')], max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Announcement Categories',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=400)),
                ('title_ar', models.CharField(blank=True, max_length=400)),
                ('title_ur', models.CharField(blank=True, max_length=400)),
                ('body_en', ckeditor.fields.RichTextField()),
                ('body_ar', ckeditor.fields.RichTextField(blank=True)),
                ('body_ur', ckeditor.fields.RichTextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='announcements.announcementcategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
    ]
