# Generated by Django 5.2.12 on 2026-04-01 02:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='body_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_location',
            field=models.CharField(blank=True, help_text='Location / venue', max_length=300),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_fa',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text='Raw iframe embed code for any video platform'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube live/recording link'),
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='title_ur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcementcategory',
            name='slug',
            field=models.CharField(choices=[('statement', 'Statement'), ('message', 'Issued Message'), ('event', 'Event')], max_length=20, unique=True),
        ),
    ]
