# Generated by Django 5.2.12 on 2026-04-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_add_event_gender_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_en', models.CharField(max_length=200, verbose_name='Author name (EN)')),
                ('author_name_ar', models.CharField(blank=True, max_length=200, verbose_name='Author name (AR)')),
                ('author_name_ur', models.CharField(blank=True, max_length=200, verbose_name='Author name (UR)')),
                ('author_name_fa', models.CharField(blank=True, max_length=200, verbose_name='Author name (FA)')),
                ('author_title_en', models.CharField(blank=True, help_text='e.g. Student, Parent, Alumnus, Visiting Scholar', max_length=200, verbose_name='Author title / role (EN)')),
                ('author_title_ar', models.CharField(blank=True, max_length=200, verbose_name='Author title (AR)')),
                ('author_title_ur', models.CharField(blank=True, max_length=200, verbose_name='Author title (UR)')),
                ('author_title_fa', models.CharField(blank=True, max_length=200, verbose_name='Author title (FA)')),
                ('author_photo', models.ImageField(blank=True, help_text='Optional portrait photo', null=True, upload_to='testimonials/photos/')),
                ('quote_en', models.TextField(verbose_name='Quote (EN)')),
                ('quote_ar', models.TextField(blank=True, verbose_name='Quote (AR)')),
                ('quote_ur', models.TextField(blank=True, verbose_name='Quote (UR)')),
                ('quote_fa', models.TextField(blank=True, verbose_name='Quote (FA)')),
                ('description_en', models.TextField(blank=True, verbose_name='Full description (EN)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Full description (AR)')),
                ('description_ur', models.TextField(blank=True, verbose_name='Full description (UR)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Full description (FA)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this testimonial on the home page (up to 4 featured displayed)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from all pages')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = displayed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
