# Generated by Django 5.2.12 on 2026-03-29 03:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('resource_type', models.CharField(choices=[('text', 'Text / Article'), ('pdf', 'PDF'), ('audio', 'Audio Recitation'), ('video', 'Video')], default='text', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='quran/files/')),
                ('external_url', models.URLField(blank=True)),
                ('surah_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('surah_name', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quran Resource',
                'ordering': ['-created_at'],
            },
        ),
    ]
