# Generated by Django 5.2.12 on 2026-03-29 03:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('tafsir', 'Tafsīr (Quranic Exegesis)'), ('hadith', 'Hadith (Prophetic Traditions)'), ('fiqh', 'Fiqh (Jurisprudence)'), ('usul', 'Usūl al-Fiqh (Principles of Jurisprudence)'), ('kalam', 'Kalām & ʿAqīdah (Theology & Creed)'), ('akhlaq', 'Akhlāq (Ethics)'), ('rational', 'Rational Sciences (Logic & Philosophy)'), ('arabic', 'Language & Literature (Arabic, English, Persian)')], max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('description_en', ckeditor.fields.RichTextField(blank=True)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='lessons.subject')),
            ],
            options={
                'verbose_name_plural': 'Lesson Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('lesson_number', models.PositiveIntegerField(default=1)),
                ('content_en', ckeditor.fields.RichTextField(blank=True)),
                ('content_ar', ckeditor.fields.RichTextField(blank=True)),
                ('content_ur', ckeditor.fields.RichTextField(blank=True)),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('mixed', 'Mixed')], default='text', max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lessons/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons/video/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessonseries')),
            ],
            options={
                'ordering': ['lesson_number'],
                'unique_together': {('series', 'lesson_number')},
            },
        ),
    ]
