# Generated by Django 5.2.12 on 2026-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_ur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(choices=[('tafsir', 'Tafsīr (Quranic Exegesis)'), ('hadith', 'Hadith (Prophetic Traditions)'), ('fiqh', 'Fiqh (Jurisprudence)'), ('usul', 'Usūl al-Fiqh (Principles of Jurisprudence)'), ('kalam', 'Kalām & ʿAqīdah (Theology & Creed)'), ('akhlaq', 'Akhlāq (Ethics)'), ('rational', 'Rational Sciences (Logic & Philosophy)'), ('arabic', 'Language & Literature (Arabic, English, Persian)')], max_length=20, unique=True),
        ),
    ]
