# Generated by Django 5.2.12 on 2026-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_add_quran_language_subject_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(choices=[('quran', 'Qurʾān Sciences (Tajweed, Hifz, Tafsir)'), ('tafsir', 'Tafsīr (Quranic Exegesis)'), ('hadith', 'Hadith (Prophetic Traditions)'), ('fiqh', 'Fiqh (Jurisprudence)'), ('usul', 'Usūl al-Fiqh (Principles of Jurisprudence)'), ('kalam', 'Kalām & ʿAqīdah (Theology & Creed)'), ('akhlaq', 'Akhlāq (Ethics)'), ('rational', 'Rational Sciences (Logic & Philosophy)'), ('language', 'Language & Literature (Arabic, English, Persian)')], max_length=20, unique=True),
        ),
    ]
