# Generated by Django 5.2.12 on 2026-04-01 13:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_arabic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonseries',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonseries',
            name='description_fa',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonseries',
            name='description_ur',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonseries',
            name='title_fa',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lessonseries',
            name='title_ur',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
